# Generated by Django 2.0.2 on 2018-06-12 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO `billing_purse` (`user_id`,`balance`) VALUES (1,300);
            INSERT INTO `billing_purse` (`user_id`,`balance`) VALUES (6,360);
            INSERT INTO `billing_purse` (`user_id`,`balance`) VALUES (9,720);
            INSERT INTO `billing_purse` (`user_id`,`balance`) VALUES (90,600);
            INSERT INTO `billing_purse` (`user_id`,`balance`) VALUES (111,29984);
            INSERT INTO `billing_purse` (`user_id`,`balance`) VALUES (1567,3400);
            INSERT INTO `billing_purse` (`user_id`,`balance`) VALUES (8195,5040);
            INSERT INTO `billing_purse` (`user_id`,`balance`) VALUES (10137,300);
            INSERT INTO `billing_purse` (`user_id`,`balance`) VALUES (10149,720);
        """),
        migrations.RunSQL("""
            INSERT INTO `billing_history` (`id`,`value`,`date`,`comment`,`user_id`) VALUES (38,29984,'2018-06-12 05:30:25','Перенос средств со Svem.ru',111);
            INSERT INTO `billing_history` (`id`,`value`,`date`,`comment`,`user_id`) VALUES (39,5040,'2018-06-12 05:30:52','Перенос средств со Svem.ru',8195);
            INSERT INTO `billing_history` (`id`,`value`,`date`,`comment`,`user_id`) VALUES (40,3400,'2018-06-12 05:31:02','Перенос средств со Svem.ru',1567);
            INSERT INTO `billing_history` (`id`,`value`,`date`,`comment`,`user_id`) VALUES (41,720,'2018-06-12 05:31:35','Перенос средств со Svem.ru',9);
            INSERT INTO `billing_history` (`id`,`value`,`date`,`comment`,`user_id`) VALUES (42,720,'2018-06-12 05:31:43','Перенос средств со Svem.ru',10149);
            INSERT INTO `billing_history` (`id`,`value`,`date`,`comment`,`user_id`) VALUES (43,600,'2018-06-12 05:31:51','Перенос средств со Svem.ru',90);
            INSERT INTO `billing_history` (`id`,`value`,`date`,`comment`,`user_id`) VALUES (44,360,'2018-06-12 05:32:02','Перенос средств со Svem.ru',6);
            INSERT INTO `billing_history` (`id`,`value`,`date`,`comment`,`user_id`) VALUES (45,300,'2018-06-12 05:32:09','Перенос средств со Svem.ru',1);
            INSERT INTO `billing_history` (`id`,`value`,`date`,`comment`,`user_id`) VALUES (46,300,'2018-06-12 05:32:15','Перенос средств со Svem.ru',10137);
        """)
    ]
