# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Электронный ящик')),
                ('first_name', models.CharField(blank=True, max_length=32, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=32, verbose_name='last name')),
                ('patronymic', models.CharField(blank=True, max_length=32, verbose_name='Отчество')),
                ('is_staff', models.BooleanField(default=False, help_text='Указывает, может ли пользователь войти в административный сайт.', verbose_name='Статус персонала')),
                ('is_active', models.BooleanField(default=True, help_text='Указывает, должен ли этот пользователь считаться активным.Снимите этот флажок, а не удаляйте аккаунты.', verbose_name='Активный')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Клиент'), (2, 'Юрист'), (3, 'Редактор')], db_index=True, default=1, help_text='Выбирите «Юрист», если Вы оказываете юридические услуги; или «Клиент», если хотите получать их.', verbose_name='Тип учётной записи')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
