# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlo_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=16, unique=True, verbose_name='Ключ на латинице')),
                ('value', models.CharField(max_length=16, verbose_name='Название роли')),
                ('description', models.TextField(blank=True, verbose_name='Описание роли')),
                ('have_profile', models.BooleanField(default=False, verbose_name='Имеет ли расширенный профайл')),
            ],
            options={
                'verbose_name': 'Тип учётной записи',
                'verbose_name_plural': 'Типы учётных записей',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(db_index=True, default=1, help_text='Выбирите «Юрист», если Вы оказываете юридические услуги; или «Клиент», если хотите получать их.', to='mlo_auth.Roles', verbose_name='Тип учётной записи'),
        ),
    ]
