# Generated by Django 2.0.2 on 2018-03-10 08:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entry', '0011_auto_20180310_1148'),
        ('mlo_auth', '0003_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('value', models.SmallIntegerField(verbose_name='Балл')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Entry', verbose_name='Ответ')),
                ('user', models.ForeignKey(help_text='Пользователь, который поставил отметку', on_delete=django.db.models.deletion.CASCADE, to='mlo_auth.User', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(verbose_name='Текст отзыва')),
                ('like', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='review.Likes')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('entry', 'user')},
        ),
    ]
