# Generated by Django 2.0.2 on 2018-05-16 01:14

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entry', '0041_auto_20180516_0413'),
        ('rubric', '0013_rubric_slug2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entry.Entry')),
                ('title', models.CharField(max_length=160, verbose_name='Заголовок')),
                ('status', django_mysql.models.EnumField(choices=[('deleted', 'deleted'), ('public', 'public'), ('blocked', 'blocked'), ('draft', 'draft')], db_index=True, default='public', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
            bases=('entry.entry', models.Model),
        ),
        migrations.CreateModel(
            name='Dir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название раздела', max_length=128, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Описание', null=True, verbose_name='Description')),
                ('slug', models.CharField(max_length=128, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Раздел статей',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='dir',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='article.Dir'),
        ),
        migrations.AddField(
            model_name='article',
            name='rubric',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rubric.Rubric', verbose_name='Рубрика'),
        ),
    ]
