# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlo_auth', '0002_auto_20171129_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Клиент'), (2, 'Юрист')], db_index=True, default=1, help_text='Выбирите «Юрист», если Вы оказываете юридические услуги; или «Клиент», если хотите получать их.', verbose_name='Тип учётной записи'),
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
