# Generated by Django 2.0 on 2017-12-19 19:43

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sxgeo', '0002_auto_20171219_1446'),
        ('mlo_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('date', models.DateField(verbose_name='Дата')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('problem', models.TextField(help_text='Проблема, с которой столкнулся клиент', verbose_name='Проблема')),
                ('solution', models.TextField(help_text='Какие действия были предприняты, чтобы решить проблему', verbose_name='Решение')),
                ('result', models.TextField(help_text='Какого результат достигли', verbose_name='Результат')),
                ('profit', models.IntegerField(blank=True, help_text='Материальная выгода клиента', null=True, verbose_name='Выгода')),
                ('file', models.FileField(blank=True, upload_to='account/case/%Y/%m/%d', verbose_name='Файл')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlo_auth.User', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=128, verbose_name='Название учебного заведения')),
                ('faculty', models.CharField(max_length=64, verbose_name='Факультет')),
                ('specialty', models.CharField(max_length=64, verbose_name='Специальность')),
                ('finish', models.PositiveSmallIntegerField(blank=True, verbose_name='Год выпуска')),
                ('diplom', models.ImageField(blank=True, upload_to='account/education/%Y/%m/', verbose_name='Копия диплома')),
                ('checked', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlo_auth.User', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Место работы')),
                ('position', models.CharField(max_length=128, verbose_name='Должность')),
                ('description', models.TextField(blank=True, max_length=1024, verbose_name='Описание организации')),
                ('site', models.URLField(blank=True, verbose_name='Сайт')),
                ('start', models.PositiveSmallIntegerField(verbose_name='Год начала работы')),
                ('finish', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год окончания работы')),
                ('doc', models.ImageField(blank=True, upload_to='account/experience/%Y/%m/', verbose_name='Документ подтверждающий трудовую деятельность')),
                ('checked', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlo_auth.User', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('sex', models.CharField(blank=True, choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1, null=True, verbose_name='Пол')),
                ('orig', image_cropping.fields.ImageCropField(blank=True, upload_to='account/photo/%Y/%m/', verbose_name='Оригинал')),
                ('photo', image_cropping.fields.ImageRatioField('orig', '600x720', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Фото профиля')),
                ('pic', image_cropping.fields.ImageRatioField('orig', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Миниатюра')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sxgeo.Cities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlo_auth.User', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информация',
            },
        ),
    ]
