# Generated by Django 2.0 on 2018-02-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='info',
            name='signature',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Подпись под ответами'),
        ),
        migrations.AddField(
            model_name='info',
            name='status',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Статус'),
        ),
    ]
