# Generated by Django 2.0 on 2018-02-06 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlo_auth', '0002_auto_20180206_0951'),
        ('account', '0002_auto_20180206_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления данных')),
                ('type', models.CharField(choices=[('E', 'Элетронный ящик'), ('P', 'Телефон'), ('A', 'Адресс'), ('S', 'Сайт')], db_index=True, default='E', max_length=1, verbose_name='Тип')),
                ('value', models.CharField(max_length=128, verbose_name='Значение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlo_auth.User', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.AlterField(
            model_name='case',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления данных'),
        ),
        migrations.AlterField(
            model_name='education',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления данных'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления данных'),
        ),
        migrations.AlterField(
            model_name='info',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления данных'),
        ),
    ]
