# Generated by Django 2.0 on 2018-02-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlo_auth', '0002_auto_20180206_0951'),
        ('account', '0003_auto_20180206_1201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
