# Generated by Django 2.0 on 2018-02-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180206_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('E', 'Электронный ящик'), ('P', 'Телефон'), ('A', 'Адрес'), ('S', 'Сайт')], db_index=True, default='E', max_length=1, verbose_name='Тип'),
        ),
    ]
