# Generated by Django 2.0 on 2018-02-18 15:17

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mlo_auth', '0002_auto_20180206_0951'),
        ('account', '0005_auto_20180212_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('value', models.IntegerField(verbose_name='Балл')),
            ],
        ),
        migrations.CreateModel(
            name='RatingTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, verbose_name='Ключ')),
                ('description', models.TextField(verbose_name='Описание')),
                ('value', models.IntegerField(verbose_name='Балл')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='account.RatingTypes'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlo_auth.User', verbose_name='Пользователь'),
        ),
    ]
