# Generated by Django 2.0 on 2018-02-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180218_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг, балл', 'verbose_name_plural': 'Рейтинг, баллы'},
        ),
        migrations.AlterModelOptions(
            name='ratingtypes',
            options={'verbose_name': 'Типы рейтинга', 'verbose_name_plural': 'Типы рейтинга'},
        ),
        migrations.AlterField(
            model_name='ratingtypes',
            name='value',
            field=models.IntegerField(editable=False, verbose_name='Балл'),
        ),
    ]
