# Generated by Django 2.0 on 2018-02-19 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20180218_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingresult',
            options={'verbose_name': 'Рейтинг: сумма балов', 'verbose_name_plural': 'Рейтинг: сумма балов'},
        ),
        migrations.AlterModelOptions(
            name='ratingtypes',
            options={'verbose_name': 'Рейтинг: тип баллов', 'verbose_name_plural': 'Рейтинг: типы баллов'},
        ),
        migrations.AlterField(
            model_name='case',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='mlo_auth.User', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='mlo_auth.User', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='mlo_auth.User', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='mlo_auth.User', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='info',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='mlo_auth.User', verbose_name='Пользователь'),
        ),
    ]
