# Generated by Django 2.0 on 2018-02-19 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20180219_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='last_update',
        ),
        migrations.AlterField(
            model_name='info',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='mlo_auth.User', verbose_name='Пользователь'),
        ),
    ]
