# Generated by Django 2.0 on 2018-03-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20180302_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Должность'),
        ),
    ]
