# Generated by Django 2.0.2 on 2018-03-03 17:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20180303_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Телефон'),
        ),
    ]
