# Generated by Django 2.0.2 on 2018-03-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_info_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='phone',
        ),
    ]
