# Generated by Django 2.0.2 on 2018-03-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20180306_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='city',
        ),
    ]
