# Generated by Django 2.0.2 on 2018-03-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20180316_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
