# Generated by Django 2.0.2 on 2018-03-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20180320_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='problem',
            field=models.TextField(blank=True, help_text='Проблема, с которой столкнулся клиент', null=True, verbose_name='Проблема'),
        ),
        migrations.AlterField(
            model_name='case',
            name='result',
            field=models.TextField(blank=True, help_text='Какого результат достигли', null=True, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='case',
            name='solution',
            field=models.TextField(blank=True, help_text='Какие действия были предприняты, чтобы решить проблему', null=True, verbose_name='Решение'),
        ),
        migrations.AlterField(
            model_name='ratingtypes',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
    ]
