# Generated by Django 2.0.2 on 2018-03-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20180322_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='status',
        ),
        migrations.AddField(
            model_name='info',
            name='short',
            field=models.CharField(blank=True, help_text='Напишите краткий рекламный текст о себе, в чём специализируетесь, какие услуги оказываете. Размещается на карточках на странице профиля.', max_length=160, null=True, verbose_name='Короткая информация о себе'),
        ),
        migrations.AlterField(
            model_name='info',
            name='about',
            field=models.TextField(blank=True, help_text='Несколько абзацев, размещается на странице профиля.', null=True, verbose_name='О себе'),
        ),
    ]
