# Generated by Django 2.0.2 on 2018-03-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20180324_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='status',
            field=models.CharField(blank=True, help_text='Например: «Семейный юрист», «Юрист по трудовым спорам», «Адвокат по земельным вопросам в Уфе». до 64 символов, можно указать регион.', max_length=64, null=True, verbose_name='Подзаголовок-статус'),
        ),
        migrations.AlterField(
            model_name='info',
            name='short',
            field=models.CharField(blank=True, help_text='Напишите краткий рекламный текст о себе, в чём специализируетесь, какие услуги оказываете. Размещается на карточках на странице профиля. Нельзя указывать контактные данные!', max_length=160, null=True, verbose_name='Короткая информация о себе'),
        ),
    ]
