# Generated by Django 2.0.2 on 2018-03-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20180324_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='status',
            field=models.CharField(blank=True, help_text='Например: «Семейный юрист», «Юрист по трудовым спорам», «Адвокат по земельным вопросам в Уфе». до 64 символов, можно указать регион. Нельзя указывать контактные данные!', max_length=64, null=True, verbose_name='Подзаголовок-статус'),
        ),
    ]
