# Generated by Django 2.0.2 on 2018-04-23 00:18

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_merge_20180325_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='about',
            field=models.TextField(blank=True, help_text='Несколько абзацев о себе, размещается на странице профиля.', null=True, verbose_name='Подробно'),
        ),
        migrations.AlterField(
            model_name='info',
            name='orig',
            field=image_cropping.fields.ImageCropField(blank=True, help_text='Вначале загрузите файл фотографии, нажмите на кнопку «Сохранить данные», потом отредактируйте область видимости для портретной и квадратной миниатюры. И ещё раз сохраните.', upload_to='account/photo/%Y/%m/', verbose_name='Оригинал'),
        ),
        migrations.AlterField(
            model_name='info',
            name='short',
            field=models.CharField(blank=True, help_text='Краткий рекламный текст о себе, в чём специализируетесь, какие услуги оказываете. Размещается на карточках и на странице профиля. Нельзя указывать контактные данные! Максимум 160 символов.', max_length=160, null=True, verbose_name='Коротко о себе'),
        ),
        migrations.AlterField(
            model_name='info',
            name='signature',
            field=models.CharField(blank=True, help_text='Подпись может выводиться под ответом.', max_length=128, null=True, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='info',
            name='status',
            field=models.CharField(blank=True, help_text='Например: «Семейный юрист», «Юрист по трудовым спорам», «Адвокат по земельным вопросам в Уфе». до 64 символов, можно указать регион. Нельзя указывать контактные данные!', max_length=64, null=True, verbose_name='Статус'),
        ),
    ]
