# Generated by Django 2.0.2 on 2018-04-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20180423_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='answer_count',
            field=models.IntegerField(default=0, verbose_name='Количество консультаций'),
        ),
        migrations.AddField(
            model_name='info',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name='Количество отзывов'),
        ),
        migrations.AddField(
            model_name='info',
            name='stage',
            field=models.IntegerField(default=0, help_text='Считается на основе опыта работы (Experience).', verbose_name='Стаж, лет'),
        ),
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(blank=True, help_text='Например: «Семейный юрист», «Юрист по трудовым спорам», «Адвокат по земельным вопросам в Уфе». до 64 символов, можно указать регион. Нельзя указывать контактные данные!', max_length=64, null=True, verbose_name='Заголовок'),
        ),
    ]
