# Generated by Django 2.0.2 on 2018-06-01 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0013_rubric_slug2'),
        ('mlo_auth', '0008_auto_20180516_0644'),
        ('account', '0029_auto_20180423_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_rubrics', models.ManyToManyField(to='rubric.Rubric')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlo_auth.User', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
