# Generated by Django 2.0.2 on 2018-06-10 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_auto_20180601_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='question_rubrics',
            new_name='rubrics',
        ),
    ]
