# Generated by Django 2.0.2 on 2018-06-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_auto_20180610_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='ym_purpose',
            field=models.CharField(blank=True, help_text='Номер счёта Яндекс.Денег.', max_length=15, null=True, verbose_name='Номер счета'),
        ),
    ]
