# Generated by Django 2.0.2 on 2018-04-08 08:15

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields
import django_mysql.models
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entry', '0030_auto_20180407_1105'),
        ('mlo_auth', '0006_user_is_expert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_mysql.models.EnumField(choices=[('new', 'Новая'), ('paid', 'Оплачена'), ('payment_confirmed', 'Оплата подтверждена'), ('inwork', 'В работе'), ('answered', 'Ответ эксперта'), ('addquestion', 'Дополнительный вопрос'), ('closed', 'Завершена'), ('canceled', 'Отменена')], db_index=True, default='new', verbose_name='Статус')),
                ('cost', models.PositiveIntegerField(default=800, verbose_name='Цена консультации')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата поступления оплаты')),
                ('answered_date', models.DateTimeField(blank=True, help_text='Когда эксперт подготовит консультацию', null=True, verbose_name='Дата ответа')),
            ],
            options={
                'verbose_name': 'Платная консультация',
                'verbose_name_plural': 'Платные консультации',
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('expert', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, primary_key=True, serialize=False, to='mlo_auth.User', verbose_name='Эксперт')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок в очереди')),
                ('is_active', models.BooleanField(verbose_name='Активность эксперта в очереди')),
            ],
            options={
                'verbose_name': 'Очередь экспертов',
                'verbose_name_plural': 'Очередь экспертов',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('expert', models.OneToOneField(on_delete=django.db.models.fields.NOT_PROVIDED, primary_key=True, serialize=False, to='mlo_auth.User')),
                ('is_available', models.BooleanField(default=True, help_text='Я готов принимать заявки на платные консультации.', verbose_name='Принимать заявки')),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/Moscow', verbose_name='Временная зона')),
                ('begin', models.TimeField(default='00:00:00', help_text='Пожалуйста, вводите время по МСК.', verbose_name='Начало рабочего дня')),
                ('end', models.TimeField(default='23:59:59', help_text='Пожалуйста, вводите время по МСК.', verbose_name='Конец рабочего дня')),
                ('weekend', models.BooleanField(default=True, help_text='Если не хотите принимать заявки в выходные дни (суббота, воскресенье), то снимите флажок.', verbose_name='Принимать заявки в выходные дни')),
            ],
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_mysql.models.EnumField(choices=[('new', 'Новая'), ('paid', 'Оплачена'), ('payment_confirmed', 'Оплата подтверждена'), ('inwork', 'В работе'), ('answered', 'Ответ эксперта'), ('addquestion', 'Дополнительный вопрос'), ('closed', 'Завершена'), ('canceled', 'Отменена')], db_index=True, verbose_name='Статус')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата принятия состояния')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Question')),
            ],
            options={
                'verbose_name': 'Журнал состояний',
                'verbose_name_plural': 'Журнал состояний',
            },
        ),
        migrations.AddField(
            model_name='advice',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.NOT_PROVIDED, to='mlo_auth.User', verbose_name='Эксперт'),
        ),
        migrations.AddField(
            model_name='advice',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advice', to='entry.Question'),
        ),
    ]
