# Generated by Django 2.0.2 on 2018-03-20 13:43

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entry', '0015_auto_20180320_1005'),
        ('mlo_auth', '0004_user_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_mysql.models.EnumField(choices=[('new', 'Новая'), ('paid', 'Оплачена'), ('inwork', 'В работе'), ('answered', 'Есть ответ'), ('closed', 'Завершена'), ('canceled', 'Отменена')], db_index=True, default='new', verbose_name='Статус')),
                ('cost', models.PositiveIntegerField(verbose_name='Цена консультации')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.NOT_PROVIDED, to='mlo_auth.User', verbose_name='Эксперт')),
                ('question', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, related_name='advice', to='entry.Question')),
            ],
            options={
                'verbose_name': 'Платная консультация',
                'verbose_name_plural': 'Платные консультации',
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_mysql.models.EnumField(choices=[('new', 'Новая'), ('paid', 'Оплачена'), ('inwork', 'В работе'), ('answered', 'Есть ответ'), ('closed', 'Завершена'), ('canceled', 'Отменена')], db_index=True, verbose_name='Статус')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата принятия состояния')),
                ('advice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advice.Advice')),
            ],
            options={
                'verbose_name': 'Платные консультации: журнал состояний',
                'verbose_name_plural': 'Платные консультации: журнал состояний',
            },
        ),
    ]
