# Generated by Django 2.0.2 on 2018-03-20 14:44

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mlo_auth', '0004_user_city'),
        ('advice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('expert', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, primary_key=True, serialize=False, to='mlo_auth.User', verbose_name='Эксперт')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок в очереди')),
                ('is_active', models.BooleanField(verbose_name='Активность эксперта')),
            ],
        ),
        migrations.AlterModelOptions(
            name='statuslog',
            options={'verbose_name': 'Журнал состояний', 'verbose_name_plural': 'Журнал состояний'},
        ),
    ]
