# Generated by Django 2.0.2 on 2018-05-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0002_auto_20180423_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='cost',
            field=models.PositiveIntegerField(default=100, verbose_name='Цена консультации'),
        ),
    ]
