# Generated by Django 2.0.2 on 2018-05-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0003_auto_20180509_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='cost',
            field=models.PositiveIntegerField(default=5, verbose_name='Цена консультации'),
        ),
    ]
