# Generated by Django 2.0.2 on 2018-03-21 05:17

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mlo_auth', '0004_user_city'),
        ('advice', '0003_auto_20180321_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduler',
            name='id',
        ),
        migrations.AddField(
            model_name='scheduler',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.fields.NOT_PROVIDED, primary_key=True, serialize=False, to='mlo_auth.User'),
            preserve_default=False,
        ),
    ]
