# Generated by Django 2.0.2 on 2018-05-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0004_auto_20180516_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='overdue_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время просрочки заявки юристом'),
        ),
        migrations.AlterField(
            model_name='advice',
            name='cost',
            field=models.PositiveIntegerField(default=800, verbose_name='Цена консультации'),
        ),
    ]
