# Generated by Django 2.0.2 on 2018-03-21 06:28

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0004_auto_20180321_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='all_time',
            field=models.BooleanField(default=True, help_text='Если не хотите принимать заявки круглосуточно, то снимите флажок и установите рабочий временной промежуток. Заявки будут приходить только в это время.', verbose_name='Принимать заявки 24 часа'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='begin',
            field=models.TimeField(default='00:00:00', help_text='Пожалуйста, вводите время по МСК.', verbose_name='Начало рабочего дня'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='end',
            field=models.TimeField(default='23:59:59', help_text='Пожалуйста, вводите время по МСК.', verbose_name='Конец рабочего дня'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Europe/Moscow', verbose_name='Временная зона'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='weekend',
            field=models.BooleanField(default=True, help_text='Если не хотите принимать заявки в выходные дни (суббота, воскресенье), то снимите флажок.', verbose_name='Принимать заявки в выходные дни'),
        ),
    ]
