# Generated by Django 2.0.2 on 2018-03-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0005_auto_20180321_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'ordering': ('order',), 'verbose_name': 'Очередь экспертов', 'verbose_name_plural': 'Очередь экспертов'},
        ),
    ]
