# Generated by Django 2.0.2 on 2018-03-22 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0006_auto_20180322_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduler',
            name='all_time',
        ),
    ]
