# Generated by Django 2.0.2 on 2018-05-31 03:23

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0006_auto_20180529_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='overdue_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Время, когда заявка будет считаться просроченной и назначен новый эксперт', null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='expert',
            field=models.OneToOneField(on_delete=django.db.models.fields.NOT_PROVIDED, primary_key=True, serialize=False, to='mlo_auth.User', verbose_name='Эксперт'),
        ),
    ]
