# Generated by Django 2.0.2 on 2018-03-23 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0007_remove_scheduler_all_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduler',
            old_name='user',
            new_name='expert',
        ),
    ]
