# Generated by Django 2.0.2 on 2018-03-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0008_auto_20180323_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Я готов принимать заявки на платные консультации.', verbose_name='Принимать заявки'),
        ),
    ]
