# Generated by Django 2.0.2 on 2018-03-23 14:23

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0010_auto_20180323_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время поступления оплаты'),
        ),
        migrations.AlterField(
            model_name='advice',
            name='status',
            field=django_mysql.models.EnumField(choices=[('new', 'Новая'), ('paid', 'Оплачена'), ('inwork', 'В работе'), ('answered', 'Ответ эксперта'), ('addquestion', 'Дополнительный вопрос'), ('closed', 'Завершена'), ('canceled', 'Отменена')], db_index=True, default='new', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='status',
            field=django_mysql.models.EnumField(choices=[('new', 'Новая'), ('paid', 'Оплачена'), ('inwork', 'В работе'), ('answered', 'Ответ эксперта'), ('addquestion', 'Дополнительный вопрос'), ('closed', 'Завершена'), ('canceled', 'Отменена')], db_index=True, verbose_name='Статус'),
        ),
    ]
