# Generated by Django 2.0.2 on 2018-03-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0011_auto_20180323_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='answered_date',
            field=models.DateTimeField(blank=True, help_text='Когда эксперт подготовит консультацию', null=True, verbose_name='Дата ответа'),
        ),
        migrations.AlterField(
            model_name='advice',
            name='cost',
            field=models.PositiveIntegerField(default=800, verbose_name='Цена консультации'),
        ),
        migrations.AlterField(
            model_name='advice',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата поступления оплаты'),
        ),
    ]
