# Generated by Django 2.0.2 on 2018-03-25 10:23

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0013_auto_20180325_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='status',
            field=django_mysql.models.EnumField(choices=[('new', 'Новая'), ('paid', 'Оплачена'), ('payment_confirmed', 'Оплата подтверждена'), ('inwork', 'В работе'), ('answered', 'Ответ эксперта'), ('addquestion', 'Дополнительный вопрос'), ('closed', 'Завершена'), ('canceled', 'Отменена')], db_index=True, default='new', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='status',
            field=django_mysql.models.EnumField(choices=[('new', 'Новая'), ('paid', 'Оплачена'), ('payment_confirmed', 'Оплата подтверждена'), ('inwork', 'В работе'), ('answered', 'Ответ эксперта'), ('addquestion', 'Дополнительный вопрос'), ('closed', 'Завершена'), ('canceled', 'Отменена')], db_index=True, verbose_name='Статус'),
        ),
    ]
