# Generated by Django 2.0.2 on 2018-03-27 08:32

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0014_auto_20180325_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.fields.NOT_PROVIDED, related_name='advice', to='entry.Question'),
        ),
    ]
