# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0008_auto_20171127_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_count',
        ),
    ]
