# Generated by Django 2.0 on 2017-12-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubric',
            options={'ordering': ('name',), 'verbose_name': 'Рубрика', 'verbose_name_plural': 'Рубрики'},
        ),
    ]
