# Generated by Django 2.0 on 2018-02-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0002_auto_20171215_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubric',
            options={'ordering': ('level', 'name'), 'verbose_name': 'Рубрика', 'verbose_name_plural': 'Рубрики'},
        ),
    ]
