# Generated by Django 2.0 on 2018-02-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0003_auto_20180218_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='call_to_action',
            field=models.CharField(blank=True, help_text='Призыв к действию. Например: Проконсультаруйся сжилищным юристом онлайн', max_length=128, verbose_name='Call to action'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='content',
            field=models.TextField(blank=True, help_text='Содержание, статья', verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='h1',
            field=models.CharField(blank=True, help_text='Заголовок h1', max_length=128, verbose_name='H1'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='title',
            field=models.CharField(blank=True, help_text='Заголовок страницы', max_length=128, verbose_name='Titlet'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='description',
            field=models.TextField(blank=True, help_text='Короткое описание', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(help_text='Название рубрики', max_length=128, unique=True, verbose_name='Name'),
        ),
    ]
