# Generated by Django 2.0 on 2018-03-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0005_auto_20180228_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='link',
            field=models.CharField(blank=True, help_text='Текст для ссылок и навигации', max_length=128, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='advice_on',
            field=models.CharField(blank=True, help_text='Юристы и адвокаты проконсультируют … платно или бесплатно', max_length=128, verbose_name='advice on'),
        ),
    ]
