# Generated by Django 2.0.2 on 2018-03-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0006_auto_20180301_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='content',
            field=models.TextField(blank=True, help_text='Содержание, статья', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='description',
            field=models.TextField(blank=True, help_text='Короткое описание', null=True, verbose_name='Description'),
        ),
    ]
