# Generated by Django 2.0.2 on 2018-04-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0007_auto_20180320_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
