# Generated by Django 2.0.2 on 2018-04-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0008_rubric_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
