# Generated by Django 2.0.2 on 2018-04-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0009_auto_20180406_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='keywords',
            field=models.TextField(blank=True, help_text='Ключевые слова для поиска вопросов', null=True, verbose_name='Ключевые слова'),
        ),
    ]
