# Generated by Django 2.0.2 on 2018-04-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0011_remove_rubric_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='is_guide_rubric',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Рубрика полезных материалов'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='is_question_rubric',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Рубрика консультаций'),
        ),
    ]
