# Generated by Django 2.0.2 on 2018-04-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0012_auto_20180411_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='slug2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
