# Generated by Django 2.0 on 2017-12-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.IntegerField()),
                ('name_ru', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128)),
                ('lat', models.DecimalField(decimal_places=5, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=5, max_digits=10)),
                ('okato', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.CharField(db_index=True, max_length=2)),
                ('continent', models.CharField(max_length=2)),
                ('name_ru', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128)),
                ('lat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lon', models.DecimalField(decimal_places=2, max_digits=6)),
                ('timezone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.CharField(max_length=7)),
                ('country', models.CharField(db_index=True, max_length=2)),
                ('name_ru', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128)),
                ('timezone', models.CharField(max_length=30)),
                ('okato', models.CharField(max_length=4)),
            ],
        ),
    ]
