# Generated by Django 2.0 on 2018-01-29 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sxgeo', '0002_auto_20171219_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
