# Generated by Django 2.0.2 on 2018-03-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sxgeo', '0003_auto_20180129_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='is_main_city',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            "UPDATE sxgeo_cities SET is_main_city = 1 where id in "
            "(524901, 498817, 519336, 472757, 1486209, 551487, 554234, 542420, 1502026, 524305, 520555, "
            "1496747, 1496153, 511196, 501175, 499099, 498677, 694423, 479561, 1508291)"
        )
    ]



