# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('pub_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Дата публикации')),
                ('status', models.IntegerField(choices=[(0, 'Удалённый'), (1, 'Черновик'), (2, 'Опубликован')], db_index=True, default=2, verbose_name='Статус')),
                ('like_count', models.IntegerField(default=0, editable=False, verbose_name='Лайки')),
                ('comment_count', models.IntegerField(default=0, editable=False, verbose_name='Количество комментариев')),
                ('title', models.CharField(max_length=160, verbose_name='Заголовок')),
                ('answer_count', models.IntegerField(default=0, editable=False, verbose_name='Количество ответов')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ('-id',),
            },
        ),
    ]
