# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 19:27
from __future__ import unicode_literals

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0001_initial'),
        ('entry', '0003_auto_20171121_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rubrics',
            field=mptt.fields.TreeManyToManyField(blank=True, to='rubric.Rubric', verbose_name='Рубрика'),
        ),
    ]
