# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_auto_20171123_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='question_set', to='mlo_auth.User'),
        ),
    ]
