# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0007_auto_20171124_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_count',
            new_name='reply_count',
        ),
        migrations.AddField(
            model_name='question',
            name='reply_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Количество ответов'),
        ),
    ]
