# Generated by Django 2.0.2 on 2018-05-17 18:52

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField(db_index=True)),
                ('lawyers_page_description', models.TextField(default=None, null=True, verbose_name='Описание для списка юристов из города')),
                ('lawyers_page_cover_orig', image_cropping.fields.ImageCropField(blank=True, upload_to='front/city_meta/%Y/%m/')),
                ('lawyers_page_cover', image_cropping.fields.ImageRatioField('lawyers_page_cover_orig', '1920x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обложка')),
            ],
        ),
    ]
