# Generated by Django 2.0.2 on 2018-05-17 20:15

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymeta',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='sxgeo.Cities'),
        ),
    ]
