# Generated by Django 2.0 on 2017-12-13 09:21

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('pub_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Дата публикации')),
                ('status', models.IntegerField(choices=[(0, 'Удалённый'), (1, 'Черновик'), (2, 'Опубликован')], db_index=True, default=2, verbose_name='Статус')),
                ('like_count', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Лайки')),
                ('reply_count', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Количество ответов')),
                ('entry_id', models.PositiveIntegerField(db_index=True)),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
            managers=[
                ('answers', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('pub_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Дата публикации')),
                ('status', models.IntegerField(choices=[(0, 'Удалённый'), (1, 'Черновик'), (2, 'Опубликован')], db_index=True, default=2, verbose_name='Статус')),
                ('like_count', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Лайки')),
                ('reply_count', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Количество ответов')),
                ('title', models.CharField(max_length=160, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ('-id',),
            },
        ),
    ]
