# Generated by Django 2.0 on 2017-12-15 11:06

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rubric', '0002_auto_20171215_1331'),
        ('mlo_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('pub_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Дата публикации')),
                ('status', models.IntegerField(choices=[(0, 'Удалённый'), (1, 'Черновик'), (2, 'Опубликован')], db_index=True, default=2, verbose_name='Статус')),
                ('like_count', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Лайки')),
                ('reply_count', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Количество ответов')),
                ('author', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='answer_set', to='mlo_auth.User')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
            managers=[
                ('answers', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('pub_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Дата публикации')),
                ('status', models.IntegerField(choices=[(0, 'Удалённый'), (1, 'Черновик'), (2, 'Опубликован')], db_index=True, default=2, verbose_name='Статус')),
                ('like_count', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Лайки')),
                ('reply_count', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Количество ответов')),
                ('title', models.CharField(max_length=160, verbose_name='Заголовок')),
                ('author', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='question_set', to='mlo_auth.User')),
                ('rubrics', mptt.fields.TreeManyToManyField(blank=True, to='rubric.Rubric', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='on_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='entry.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entry.Answer'),
        ),
    ]
