# Generated by Django 2.0 on 2017-12-13 09:21

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rubric', '0001_initial'),
        ('mlo_auth', '0001_initial'),
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='question_set', to='mlo_auth.User'),
        ),
        migrations.AddField(
            model_name='question',
            name='rubrics',
            field=mptt.fields.TreeManyToManyField(blank=True, to='rubric.Rubric', verbose_name='Рубрика'),
        ),
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='answer_set', to='mlo_auth.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entry.Answer'),
        ),
    ]
