# Generated by Django 2.0 on 2017-12-18 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='on_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='entry.Question', verbose_name='На вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entry.Answer', verbose_name='К ответу'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='entry_set', to='mlo_auth.User', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='reply_count',
            field=models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Ответов'),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='entries/%Y/%m/%d', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entry.Answer'),
        ),
    ]
