# Generated by Django 2.0 on 2017-12-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_auto_20171218_0649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Счёт на оказание платных услуг', 'verbose_name_plural': 'Счёта'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='cost',
            field=models.PositiveIntegerField(verbose_name='Стоимость услуг (₽)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.IntegerField(choices=[('0', 'Новое'), ('1', 'Просмотрено клиентом'), ('5', 'Оплачен'), ('-1', 'Отменён')], db_index=True, default='0', verbose_name='Статус счёта'),
        ),
    ]
