# Generated by Django 2.0 on 2018-02-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_auto_20171218_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=24)),
            ],
            options={
                'verbose_name': 'Состояние платной консультации',
                'verbose_name_plural': 'Состояния платных консультаций',
            },
        ),
    ]
