# Generated by Django 2.0 on 2018-02-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_auto_20180215_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='cost',
            field=models.PositiveIntegerField(default=1000, verbose_name='Цена консультации'),
            preserve_default=False,
        ),
    ]
