# Generated by Django 2.0 on 2018-02-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_consultstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultstate',
            name='key',
            field=models.CharField(default='', max_length=24, verbose_name='Название на латинице'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultstate',
            name='state',
            field=models.CharField(max_length=24, verbose_name='Название состояния'),
        ),
    ]
