# Generated by Django 2.0 on 2018-02-12 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlo_auth', '0002_auto_20180206_0951'),
        ('entry', '0005_auto_20180212_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entry.Question')),
                ('expert', models.ManyToManyField(to='mlo_auth.User', verbose_name='Эксперт')),
            ],
            options={
                'abstract': False,
            },
            bases=('entry.question',),
        ),
        migrations.CreateModel(
            name='ConsultStateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('consult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Consult')),
                ('consult_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.ConsultState')),
            ],
        ),
        migrations.AddField(
            model_name='consult',
            name='state',
            field=models.ManyToManyField(through='entry.ConsultStateLog', to='entry.ConsultState'),
        ),
    ]
