# Generated by Django 2.0.2 on 2018-03-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0007_auto_20180303_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultstate',
            options={'verbose_name': 'Платные консультации: таблица состояний', 'verbose_name_plural': 'Платные консультации: таблица состояний'},
        ),
        migrations.AlterModelOptions(
            name='consultstatelog',
            options={'verbose_name': 'Платные консультации: журнал состояний', 'verbose_name_plural': 'Платные консультации: журнал состояний'},
        ),
        migrations.AlterModelOptions(
            name='likes',
            options={'ordering': ('-date',), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='consultstate',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
