# Generated by Django 2.0.2 on 2018-03-10 05:15

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0009_auto_20180309_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=django_mysql.models.EnumField(choices=[('deleted', 'deleted'), ('public', 'public'), ('blocked', 'blocked'), ('draft', 'draft')], db_index=True, default='public', verbose_name='Статус'),
        ),
    ]
