# Generated by Django 2.0.2 on 2018-03-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0011_auto_20180310_1148'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='answer',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='like_count',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Лайки'),
        ),
    ]
