# Generated by Django 2.0.2 on 2018-03-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0012_auto_20180316_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='reply_count',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Ответов'),
        ),
    ]
