# Generated by Django 2.0.2 on 2018-03-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0013_auto_20180316_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Key'),
        ),
    ]
