# Generated by Django 2.0.2 on 2018-03-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0014_question_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultstate',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
    ]
