# Generated by Django 2.0.2 on 2018-03-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0015_auto_20180320_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consult',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='consult',
            name='question',
        ),
        migrations.RemoveField(
            model_name='consult',
            name='state',
        ),
        migrations.RemoveField(
            model_name='consultstatelog',
            name='consult',
        ),
        migrations.RemoveField(
            model_name='consultstatelog',
            name='consult_state',
        ),
        migrations.DeleteModel(
            name='Consult',
        ),
        migrations.DeleteModel(
            name='ConsultState',
        ),
        migrations.DeleteModel(
            name='ConsultStateLog',
        ),
    ]
