# Generated by Django 2.0.2 on 2018-03-25 10:18

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0016_auto_20180320_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
