# Generated by Django 2.0.2 on 2018-03-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0018_auto_20180325_1339'),
        ('entry', '0017_auto_20180325_1318'),
    ]

    operations = [
    ]
