# Generated by Django 2.0.2 on 2018-03-27 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0019_merge_20180325_1417'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
            ],
        ),
    ]
