# Generated by Django 2.0.2 on 2018-03-28 07:10

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0020_auto_20180327_0843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('id',), 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='status',
        ),
        migrations.AddField(
            model_name='answer',
            name='status',
            field=django_mysql.models.EnumField(choices=[('deleted', 'deleted'), ('public', 'public'), ('blocked', 'blocked'), ('draft', 'draft')], db_index=True, default='public', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=django_mysql.models.EnumField(choices=[('deleted', 'deleted'), ('public', 'public'), ('blocked', 'blocked'), ('draft', 'draft')], db_index=True, default='public', verbose_name='Статус'),
        ),
    ]
