# Generated by Django 2.0.2 on 2018-03-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0021_auto_20180328_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='thread',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Ветка'),
        ),
    ]
