# Generated by Django 2.0.2 on 2018-04-03 13:54

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0007_auto_20180320_1005'),
        ('entry', '0024_question_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='rubrics',
        ),
        migrations.AddField(
            model_name='question',
            name='rubric',
            field=mptt.fields.TreeForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubric', to='rubric.Rubric', verbose_name='Рубрика'),
        ),
    ]
