# Generated by Django 2.0.2 on 2018-04-07 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0026_question_rubrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sxgeo.Cities'),
        ),
        migrations.AlterField(
            model_name='question',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True, verbose_name='Key'),
        ),
    ]
