# Generated by Django 2.0.2 on 2018-04-07 07:48
from apps.entry.models import Entry
from django.db import migrations
from django.db.models import F


def update_time(apps, schema_editor):
    Entry.objects.all().update(
        created_at=F('pub_date'),
        updated_at=F('pub_date')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0028_auto_20180407_1044'),
    ]

    operations = [
        migrations.RunPython(update_time),
    ]
