# Generated by Django 2.0.2 on 2018-04-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0029_auto_20180407_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='key',
            new_name='token',
        ),
    ]
