# Generated by Django 2.0.2 on 2018-04-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0031_sphcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additionals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='additionals',
            unique_together={('question_id', 'user_id')},
        ),
    ]
