# Generated by Django 2.0.2 on 2018-04-29 09:57

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0034_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='rubric',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rubric', to='rubric.Rubric', verbose_name='Рубрика'),
        ),
    ]
