# Generated by Django 2.0.2 on 2018-05-09 01:03

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0013_rubric_slug2'),
        ('entry', '0035_auto_20180429_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entry.Entry')),
                ('title', models.CharField(max_length=160, verbose_name='Заголовок')),
                ('status', django_mysql.models.EnumField(choices=[('deleted', 'deleted'), ('public', 'public'), ('blocked', 'blocked'), ('draft', 'draft')], db_index=True, default='public', verbose_name='Статус')),
                ('rubric', mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rubric.Rubric', verbose_name='Рубрика')),
            ],
            options={
                'abstract': False,
            },
            bases=('entry.entry', models.Model),
        ),
        migrations.RemoveField(
            model_name='question',
            name='rubrics',
        ),
        migrations.AlterField(
            model_name='question',
            name='rubric',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rubric.Rubric', verbose_name='Рубрика'),
        ),
    ]
