# Generated by Django 2.0.2 on 2018-05-09 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0036_auto_20180509_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название раздела', max_length=128, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Описание', null=True, verbose_name='Description')),
                ('slug', models.CharField(blank=True, max_length=128, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Раздел статей',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='article',
            name='dir',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='entry.Dir'),
        ),
    ]
