# Generated by Django 2.0.2 on 2018-05-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0037_auto_20180509_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dir',
            name='name',
            field=models.CharField(help_text='Название раздела', max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dir',
            name='slug',
            field=models.CharField(max_length=128, unique=True, verbose_name='Слаг'),
        ),
    ]
