# Generated by Django 2.0.2 on 2018-05-09 17:45

import apps.entry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0038_auto_20180509_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to=apps.entry.models.get_file_path, verbose_name='Файл'),
        ),
    ]
