# Generated by Django 2.0.2 on 2018-05-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0039_auto_20180509_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.CharField(default=None, editable=False, max_length=255),
        ),
    ]
