# Generated by Django 2.0.2 on 2018-05-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0041_auto_20180516_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Колличество просмотров'),
        ),
    ]
