# Generated by Django 2.0.2 on 2018-06-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0042_entry_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='cost',
            field=models.PositiveIntegerField(verbose_name='Стоимость услуги (₽)'),
        ),
    ]
