# Generated by Django 2.0 on 2018-01-29 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svem_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhash',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlo_auth.User'),
        ),
    ]
