# Generated by Django 2.0.2 on 2018-03-22 07:41

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mlo_auth', '0004_user_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rating', serialize=False, to='mlo_auth.User', verbose_name='Пользователь')),
                ('day_rate', models.IntegerField(db_index=True, verbose_name='Рейтинг за сутки')),
                ('week_rate', models.IntegerField(db_index=True, verbose_name='Рейтинг за неделю')),
                ('month_rate', models.IntegerField(db_index=True, verbose_name='Рейтинг за месяц')),
                ('rate', models.IntegerField(db_index=True, verbose_name='Рейтинг за всё время')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинг',
            },
        ),
        migrations.CreateModel(
            name='RatingScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Балл',
                'verbose_name_plural': 'Баллы',
            },
        ),
        migrations.CreateModel(
            name='RatingScoreComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=128, null=True)),
                ('rating_score', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='rating.RatingScore')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, verbose_name='Ключ')),
                ('value', models.SmallIntegerField(verbose_name='Балл')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип баллов',
                'verbose_name_plural': 'Типы баллов',
            },
        ),
        migrations.AddField(
            model_name='ratingscore',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='rating.Type', verbose_name='Тип балла'),
        ),
        migrations.AddField(
            model_name='ratingscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlo_auth.User', verbose_name='Пользователь'),
        ),
    ]
