# Generated by Django 2.0.2 on 2018-03-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ('-week_rate',), 'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинг'},
        ),
        migrations.AlterField(
            model_name='rating',
            name='day_rate',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Рейтинг за сутки'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='month_rate',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Рейтинг за месяц'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Рейтинг за всё время'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='week_rate',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Рейтинг за неделю'),
        ),
    ]
