# Generated by Django 2.0.2 on 2018-03-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_merge_20180325_1417'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='rating',
            managers=[
            ],
        ),
    ]
