# Generated by Django 2.0.2 on 2018-03-03 17:08

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mlo_auth', '0002_auto_20180206_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Телефон'),
        ),
    ]
