# Generated by Django 2.0.2 on 2018-03-12 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sxgeo', '0003_auto_20180129_0917'),
        ('mlo_auth', '0003_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sxgeo.Cities'),
        ),
    ]
