# Generated by Django 2.0.2 on 2018-04-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlo_auth', '0005_auto_20180325_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_expert',
            field=models.BooleanField(default=False, help_text='Указывает, является ли пользователь экспертом, имеющим право отвечать на платные вопросы.', verbose_name='Эксперт'),
        ),
    ]
