# Generated by Django 2.0.2 on 2018-04-23 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlo_auth', '0006_user_is_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sxgeo.Cities', verbose_name='Город'),
        ),
    ]
