# Generated by Django 2.0.2 on 2018-05-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlo_auth', '0007_auto_20180423_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='Последний визит'),
        ),
    ]
